import type { WorkerSignal } from "./types.ts";

export const workerSignals: WorkerSignal[] = [
  {
    id: "svc_checkout",
    name: "Checkout API",
    team: "Commerce Platform",
    role: "Tier 1 Revenue Service",
    location: "us-east-1",
    manager: "Maya Johnson",
    timezone: "production",
    prsOpenedLast14Days: 8,
    reviewLatencyHours: 26,
    afterHoursWorkPct: 37,
    meetingLoadHours: 14,
    focusHoursPerDay: 2.7,
    onCallPagesLast14Days: 4,
    manager1to1GapDays: 36,
    vacationDaysNext30: 3,
    asyncSentimentScore: 2.2,
    note: "Release train has a stale PR queue, two failed deploys, and repeated payment alert escalations in Slack."
  },
  {
    id: "svc_ledger",
    name: "Ledger Sync",
    team: "Finance Systems",
    role: "Critical Data Pipeline",
    location: "us-central-1",
    manager: "Rafael Kim",
    timezone: "production",
    prsOpenedLast14Days: 2,
    reviewLatencyHours: 7,
    afterHoursWorkPct: 10,
    meetingLoadHours: 5,
    focusHoursPerDay: 5.2,
    onCallPagesLast14Days: 1,
    manager1to1GapDays: 8,
    vacationDaysNext30: 0,
    asyncSentimentScore: 4.3,
    note: "Healthy release lane, low alert noise, and clear ownership on the weekly deployment window."
  },
  {
    id: "svc_identity",
    name: "Identity Gateway",
    team: "Trust Platform",
    role: "Authentication Edge",
    location: "global-edge",
    manager: "Nina Patel",
    timezone: "production",
    prsOpenedLast14Days: 5,
    reviewLatencyHours: 19,
    afterHoursWorkPct: 28,
    meetingLoadHours: 16,
    focusHoursPerDay: 3.1,
    onCallPagesLast14Days: 5,
    manager1to1GapDays: 29,
    vacationDaysNext30: 2,
    asyncSentimentScore: 2.7,
    note: "Auth incidents repeated after a config rollout and Slack escalations suggest the release needs a gate review."
  },
  {
    id: "svc_search",
    name: "Search Indexer",
    team: "Discovery",
    role: "Background Worker",
    location: "us-west-2",
    manager: "Helen Flores",
    timezone: "staging",
    prsOpenedLast14Days: 4,
    reviewLatencyHours: 11,
    afterHoursWorkPct: 16,
    meetingLoadHours: 8,
    focusHoursPerDay: 4.4,
    onCallPagesLast14Days: 0,
    manager1to1GapDays: 12,
    vacationDaysNext30: 0,
    asyncSentimentScore: 3.8,
    note: "Backfill jobs are stable and no release blockers are present for the next deploy window."
  },
  {
    id: "svc_billing",
    name: "Billing Webhooks",
    team: "Commerce Platform",
    role: "Revenue Event Processor",
    location: "eu-west-1",
    manager: "Maya Johnson",
    timezone: "production",
    prsOpenedLast14Days: 7,
    reviewLatencyHours: 31,
    afterHoursWorkPct: 34,
    meetingLoadHours: 13,
    focusHoursPerDay: 2.9,
    onCallPagesLast14Days: 3,
    manager1to1GapDays: 42,
    vacationDaysNext30: 4,
    asyncSentimentScore: 2.4,
    note: "Webhook retries, blocked PRs, and repeated deploy failures are threatening the release cut for finance customers."
  },
  {
    id: "svc_agent",
    name: "Support Agent Runtime",
    team: "AI Platform",
    role: "Gemini Agent Service",
    location: "us-east-1",
    manager: "Jordan Miles",
    timezone: "production",
    prsOpenedLast14Days: 3,
    reviewLatencyHours: 13,
    afterHoursWorkPct: 22,
    meetingLoadHours: 10,
    focusHoursPerDay: 3.7,
    onCallPagesLast14Days: 2,
    manager1to1GapDays: 20,
    vacationDaysNext30: 1,
    asyncSentimentScore: 3.1,
    note: "Inference latency recovered after the last incident, but deployment confidence is still below target."
  }
];

export const teams = ["All Domains", ...new Set(workerSignals.map((item) => item.team))];
export const connectedSources = ["GitHub", "Slack", "PagerDuty", "Jira", "Deploy Logs"];
